// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vector.proto

#include "vector.pb.h"
#include "vector.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace calculus {

static const char* VectorCalculator_method_names[] = {
  "/calculus.VectorCalculator/CrossProduct",
};

std::unique_ptr< VectorCalculator::Stub> VectorCalculator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VectorCalculator::Stub> stub(new VectorCalculator::Stub(channel));
  return stub;
}

VectorCalculator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CrossProduct_(VectorCalculator_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VectorCalculator::Stub::CrossProduct(::grpc::ClientContext* context, const ::calculus::VectorRequest& request, ::calculus::Vector* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CrossProduct_, context, request, response);
}

void VectorCalculator::Stub::experimental_async::CrossProduct(::grpc::ClientContext* context, const ::calculus::VectorRequest* request, ::calculus::Vector* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CrossProduct_, context, request, response, std::move(f));
}

void VectorCalculator::Stub::experimental_async::CrossProduct(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::calculus::Vector* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CrossProduct_, context, request, response, std::move(f));
}

void VectorCalculator::Stub::experimental_async::CrossProduct(::grpc::ClientContext* context, const ::calculus::VectorRequest* request, ::calculus::Vector* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CrossProduct_, context, request, response, reactor);
}

void VectorCalculator::Stub::experimental_async::CrossProduct(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::calculus::Vector* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CrossProduct_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::calculus::Vector>* VectorCalculator::Stub::AsyncCrossProductRaw(::grpc::ClientContext* context, const ::calculus::VectorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::calculus::Vector>::Create(channel_.get(), cq, rpcmethod_CrossProduct_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::calculus::Vector>* VectorCalculator::Stub::PrepareAsyncCrossProductRaw(::grpc::ClientContext* context, const ::calculus::VectorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::calculus::Vector>::Create(channel_.get(), cq, rpcmethod_CrossProduct_, context, request, false);
}

VectorCalculator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VectorCalculator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VectorCalculator::Service, ::calculus::VectorRequest, ::calculus::Vector>(
          [](VectorCalculator::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::calculus::VectorRequest* req,
             ::calculus::Vector* resp) {
               return service->CrossProduct(ctx, req, resp);
             }, this)));
}

VectorCalculator::Service::~Service() {
}

::grpc::Status VectorCalculator::Service::CrossProduct(::grpc::ServerContext* context, const ::calculus::VectorRequest* request, ::calculus::Vector* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace calculus

